apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs-deploy
  namespace: wikijs
  labels:
    app: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: requarks/wiki:2
          env:
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"  
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PASSWORD 
          ports:
          - containerPort: 3000
            protocol: TCP