kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/wikijs"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: wikijs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi