apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: wikijs
type: Opaque
data:
  ROOT_PASSWORD: c2VuaGFyb290ZG9iYW5jbw==
  DATABASE: d2lraWpz
  USER: d2lraWpz
  PASSWORD: c2VuaGFkb2JhbmNv