apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: wikijs
spec:
  selector:
    matchLabels:
      app: postgres-statefulset
  serviceName: "postgres-statefulset"
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres-statefulset
    spec:
      containers:
      - name: postgres
        image: postgres:12
        env:
        - name: POSTGRES_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: ROOT_PASSWORD
        - name: POSTGRES-DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PASSWORD
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim